---
output:
  md_document:
    variant: markdown_github
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "dev/figures/")
ggplot2::theme_set(ggplot2::theme_minimal())
```

# cdifdif

The goal of cdifdif is to ...

## Example

This is a basic example which shows you how to solve a common problem:

```{r}
library(cdifdif)

data("spilloverDGP")

str(spilloverDGP)

mod <- cdifdif(y1 ~ time + treat, data = spilloverDGP, dist = spilloverDGP$dist,
               maxDist = 30, delta = 1, alpha = 0.05, k = 10, verbose = FALSE)
```

We can obtain all the CV-RMSE and plot them.

```{r}
plot(mod$cvs, type = "l", main = "CV RMSEs")
```

And get the model where we obtain that error:

```{r}
nmod <- which.min(mod$cvs)
nmod

mod$cvs[[nmod]]
```

And then the model:

```{r}
library(broom) # tidy function

tidy(mod$mods[[nmod]]) 
```

5 intervals we have. We can visualize:

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(viridis)

step <- mod$steps[[nmod]]
step

cuts <- c(seq(0, 5), Inf) * step
cuts

spilloverDGP21 <- spilloverDGP %>% 
  filter(treat == 1) %>% 
  distinct(id) %>% 
  mutate(treated = "yes")

spilloverDGP22 <- spilloverDGP %>% 
  filter(treat == 0, time == 1) %>% 
  select(id, dist) %>% 
  mutate(distance = cut(dist, cuts, include.lowest = FALSE)) %>% 
  select(id, distance)

spilloverDGP <- spilloverDGP %>% 
  left_join(spilloverDGP21) %>% 
  left_join(spilloverDGP22) %>% 
  mutate(treated = ifelse(is.na(treated), "no", "yes"))
spilloverDGP  


ggplot(spilloverDGP, aes(x = time, y = y1)) +
  geom_line(aes(group = id, color = treated), alpha = 0.15) +
  geom_smooth(aes(color = treated), se = FALSE, lwd = 2, method = "lm") +
  scale_color_viridis(discrete = TRUE, end = 0.9)


spilloverDGP %>% 
  filter(treated == "no") %>%
  ggplot(aes(x = time, y = y1)) +
  geom_line(aes(group = id, color = distance), alpha = 0.15) +
  geom_smooth(aes(color = distance), se = FALSE, lwd = 2, method = "lm") +
  scale_color_viridis(discrete = TRUE) +
  labs(title = "Effect on NO treated cases by distance")
```


```{r}
# weights
set.seed(123)
ws <- runif(nrow(spilloverDGP))

mod <- cdifdif(y1 ~ time + treat, data = spilloverDGP, dist = spilloverDGP$dist,
               maxDist = 30, delta = 1, alpha = 0.05, k = 10, verbose = FALSE,
               weights = ws)
```


